### ISSUE TITLE
OnItemMovedListener provide wrong "to" position when dragged to bottom of screen from top

### ISSUE THREAD

**Issue by gauravlnx** [emileb/DragSortRecycler#12]
I have encountered this issue while playing testing it in a demo project. The details are as below:

My UI Layout:
1. Recycler view of layout_height "match_parent".
2. Individual item view height is approx. 180 dp (basically only 3 items fits on screen in portrait)
3. Drag handle view to center right (size 60x40) 
4. There are 5 items in Recycler view

Steps that I used to reproduce:
1. Drag item at position 0 to bottom of screen (inside recycler view, most probably 'to' position will be 2) and make sure it doesn't scroll and then lift the finger.
2. OnItemMovedListener reports 5 as the "to" position where it should be 2. So after calling notifyDataSetChanged(), the dragged item goes to last position in Recycler view.
3. If I let the recycler to scroll while dragging and release the view in center of the screen, reported "to" position is correct.
4. If I drag an item from bottom towards top of the screen, reported position is also correct. 

BTW thanks for your time in making this.

**Comment by emileb** [comment]
Hi,
Thanks for this report, I can reproduce the issue. Just debugging now!
Emile

**Comment by emileb** [comment]
OK I *think* this is fixed, let me know if you give it a go. Thanks.
