### ISSUE TITLE
setHasStableIds(true) method ?

### ISSUE THREAD

**Issue by u2gilles** [emileb/DragSortRecycler#13]
Your lib works fine unless I call  adapter,setHasStableIds(true), in which case my list completely screws up (duplicated items, missing items etc...).
So this is fine for me, I don't call it. 
But I am curious about why you call it in you demo activity testdragsortrecycler ?
Is it important. Do I miss something if i don't call it? How to fix the problem if I have to call it?

**Comment by emileb** [comment]
Hi,
Actually I removed this line (it's commented in the latest version).
It's not required now. If you have it set you need to make sure "public long getItemId(int position) " is implemted in your adapter, and it actually HAS stable Id's (returning position it not correct)
So no, you don't need it set.

**Comment by u2gilles** [comment]
Thanks for your prompt answer.
