### ISSUE TITLE
How to integrate this plugin with HashMap<String, String> kind of data?

### ISSUE THREAD

**Issue by azizimusa** [emileb/DragSortRecycler#17]
I had try couple of hours till now. Still cant integrate with HashMap<String, String>. Can you show me an example ?

**Comment by emileb** [comment]
Hi the library does not concern itself with how the data is stored or represented, have you got it working in a Recyclerview without sorting?

**Comment by azizimusa** [comment]
Yes it is working. But now I manage understand a bit of how to fill the data in recyclerview. Now I got new problem which is, my imageview won't allow me to drag and sort. I have pick the imageview from linearlayout. But still the problem arise. Please check my layout file. I am using imageview with an ID of #holder, at the bottom of the layout.

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal"
    android:padding="5dip" >

    
    <LinearLayout android:id="@+id/thumbnail"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:padding="3dip"
        android:layout_alignParentLeft="true"
        android:layout_marginRight="5dip">

        <ImageView
            android:id="@+id/list_image"
            android:layout_width="80dip"
            android:layout_height="match_parent"
            android:adjustViewBounds="true"
            android:src="@drawable/aed"
            android:scaleType="fitXY"
            android:layout_marginRight="20dp" />

    </LinearLayout>

    
    <TextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignTop="@+id/thumbnail"
        android:layout_toRightOf="@+id/thumbnail"
        android:text="AED"
        android:textColor="#040404"
        android:typeface="sans"
        android:textSize="20sp"
        android:textStyle="bold"
        android:paddingTop="5dp" />

    
    <TextView
        android:id="@+id/rate"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="#343434"
        android:textSize="18sp"
        android:layout_toRightOf="@+id/title"
        android:text="2.2332"
        android:paddingTop="5dp"
        android:paddingLeft="33dp" />

    
    <TextView
        android:id="@+id/conversion"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/title"
        android:textColor="#343434"
        android:textSize="18sp"
        android:layout_marginTop="1dip"
        android:layout_toRightOf="@+id/thumbnail"
        android:text="1 MYR = 0.21312"
        android:paddingTop="5dp" />

    

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentRight="false"
        android:gravity="end">

        
        <ImageView

            android:id="@+id/holder"
            android:layout_width="40dip"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_star"
            android:adjustViewBounds="true"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_gravity="right" />

    </LinearLayout>

</RelativeLayout>

**Comment by azizimusa** [comment]
Hi Emileb ! ..just to inform you that i manage to get this working smoothly !. Thanks for the plugin.

**Comment by emileb** [comment]
Great, thanks for the update!
